name = "test2"
uuid = "1d75fc34-6f69-422e-a528-17ee18e2a77a"
authors = ["yuntien lee"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
